### ISSUE TITLE
Documentation: Convention recommendation for where to place Capybara::UI class definitions.

### ISSUE THREAD

**Issue by manlycode** [collectiveidea/capybara-ui#4]
The README doesn't recommend where to place definitions in the spec directory.

**Comment by laserlemon** [comment]
Good call. That's because I don't know what to recommend yet.

I've thought:

```
▾ spec
  ▾ support
    ▾ ui
      ▾ pages
          foo_page.rb
          bar_page.rb
      ▾ elements
          foo_table.rb
          bar_form.rb
```

or maybe just:

```
▾ spec
  ▾ support
    ▾ ui
        foo_page.rb
        bar_page.rb
        foo_table.rb
        bar_form.rb
```

Thoughts?

**Comment by laserlemon** [comment]
I also like [Domino's](https://github.com/ngauthier/domino) convention of namespacing the classes:

``` ruby
module UI
  class FooPage < Capybara::UI
    # TODO
  end

  class BarPage < Capybara::UI
    # TODO
  end
end
```

**Comment by manlycode** [comment]
Support worked for me. But, convention over configuration. Amirite?

—

**Comment by laserlemon** [comment]
I'm also wondering if pages should inherit from a more descriptive class than `Capybara::UI` like `Capybara::UI::Page` which has good symmetry with `Capybara::UI::Element`.

**Comment by laserlemon** [comment]
Ultimately, it doesn't matter where you put them as long as you load them before you run your suite. By default (and in most cases), the `spec/support` directory will be automatically loaded (as instructed by `spec_helper.rb`) so anywhere inside `spec/support` is a good candidate.

**Comment by emilford** [comment]
+1 to `UI::` namespace, `spec/support/{pages,elements}`, and `Capybara::UI::Page`.

**Comment by ersatzryan** [comment]
since we don't HAVE to reference the class thanks to `page.ui` could namespace them under `Capybara::UI`

``` ruby
module Capybara::UI
  class PeoplePage < Page
  end

  class Person < Element
  end
end
```

**Comment by ersatzryan** [comment]
This also lends itself nicely to your first proposal of

```
▾ spec
  ▾ support
    ▾ ui
      ▾ pages
          foo_page.rb
          bar_page.rb
      ▾ elements
          foo_table.rb
          bar_form.rb
```

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
