### ISSUE TITLE
Path helpers don't work when specifying a path.

### ISSUE THREAD

**Issue by manlycode** [collectiveidea/capybara-ui#5]
It'd be nice to be able to user *_path helpers when setting the path for a Capybara::UI class.

**Comment by laserlemon** [comment]
I'd love for this to work too and haven't given up on the idea, but the only issue is that Capybara::UI isn't Rails-specific. So we'd want to load those helpers into Capybara::UI, but only if they're available in the first place. Capybara::UI will work with any Rack app, not just Rails.

**Comment by ersatzryan** [comment]
could make this a specific file that you have to require to get the helpers `require "capybara/ui/rails"`

**Comment by laserlemon** [comment]
Good idea.

**Comment by manlycode** [comment]
+1

—

**Comment by ersatzryan** [comment]
@laserlemon I think I have a good way forward code wise on this, but not sure how to go about testing... if you have any time free ping me

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
